### ISSUE TITLE
Documentacion: punto 12

### ISSUE THREAD

**Issue by UO270176** [Arquisoft/radarin_es1a#13]
Terms glossary

**Comment by UO270176** [comment]
Agregados primeros 4 términos , react, pods, solid y arc42 al glosario.
https://github.com/Arquisoft/radarin_es1a/commit/5c194bc1b691b80bc9dda54c34af8bfaf28f218f

**Comment by albaaparicio12** [comment]
Added WC3 and Heroku
https://github.com/Arquisoft/radarin_es1a/commit/86868c67f5422e6cc0f44781216a83b33e933e29

**Comment by UO266618** [comment]
> Ordenar alfabéticamente los términos.

Commit: https://github.com/Arquisoft/radarin_es1a/commit/96992a76c44860728ad6fbef72ed7f233a405d47

**Comment by UO266618** [comment]
> Añadido término "Server".

Commit: https://github.com/Arquisoft/radarin_es1a/commit/96992a76c44860728ad6fbef72ed7f233a405d47
