### ISSUE TITLE
Corrección Documentación: punto 5

### ISSUE THREAD

**Issue by UO266618** [Arquisoft/radarin_es1a#25]

**Comment by UO263745** [comment]
Se debe modificar las lineas en los diagramas de los apartados 5.1 y 5.2 que van desde user a user's pod

**Comment by UO263745** [comment]
Hacer el diagrama general con todos los niveles

**Comment by UO263745** [comment]
Añadir nivel 3

**Comment by UO247134** [comment]
Point number 5.3, line between **Map** and **Locations Manager** must be bidirectional
- The Location Manager must prove the information that the Map will represent
Point number 5.3, line between **Locations Manager** and **Database** must be bidirectional
- The location manager extracts user location information when required, and updates it as soon as the user refreshes the application

**Comment by UO263745** [comment]
> 
> 
> Se debe modificar las lineas en los diagramas de los apartados 5.1 y 5.2 que van desde user a user's pod

Último commit: https://github.com/Arquisoft/radarin_es1a/commit/731c691057597edefae0fa468c2ae560d55064fb

**Comment by UO263745** [comment]
> 
> 
> Añadir nivel 3

Commit: https://github.com/Arquisoft/radarin_es1a/commit/ca8f2eca56fb42eb7c34ba6b7831227e3907cdab

**Comment by UO263745** [comment]
> 
> 
> Point number 5.3, line between **Map** and **Locations Manager** must be bidirectional
> 
>     * The Location Manager must prove the information that the Map will represent
> 
> 
> Point number 5.3, line between **Locations Manager** and **Database** must be bidirectional
> 
>     * The location manager extracts user location information when required, and updates it as soon as the user refreshes the application

Commit: https://github.com/Arquisoft/radarin_es1a/commit/60055dd2d00d21d1a5c2198e528a55b03c9961b3

**Comment by kevin1123699** [comment]
La flechas de user a la aplicación no coinciden en los diagramas

**Comment by kevin1123699** [comment]
Explicación linea usuario-Pod

**Comment by UO263745** [comment]
> 
> 
> Hacer el diagrama general con todos los niveles

Commit: https://github.com/Arquisoft/radarin_es1a/commit/82f96b616826cf486db07a5015ca84a2269a4926

**Comment by UO263745** [comment]
> 
> 
> La flechas de user a la aplicación no coinciden en los diagramas

Commit: https://github.com/Arquisoft/radarin_es1a/commit/82f96b616826cf486db07a5015ca84a2269a4926

**Comment by UO266618** [comment]
Mover del punto 5.1 al 5 el diagrama general de representación conjunta de los niveles y añadir explicación.

**Comment by UO266618** [comment]
Añadir explicación de las cajas negras en el nivel 3.

**Comment by UO266618** [comment]
Cambiar la base de datos relacionada con el Locations Manager por un servidor de localizaciones. Diagrama del nivel 3.
