### ISSUE TITLE
1st Prototype: Map of locations

### ISSUE THREAD

**Issue by UO266618** [Arquisoft/radarin_es1a#30]

**Comment by kevin1123699** [comment]
Probado con https://github.com/mariusandra/pigeon-maps  pero finalmente no escogido por estar en blanco y negro, además de problemas con los marcadores.

Probado con https://www.npmjs.com/package/simple-react-google-maps y funcional pero rechazado por  tener que meter tarjeta de crédito

**Comment by UO266618** [comment]
Investigando sobre diferentes mapas interactivos que se puedan utilizar y sobre PWA.

**Comment by UO266618** [comment]
Probando funcionalidades básicas de https://developer.here.com/ como posible API para los mapas.

**Comment by albaaparicio12** [comment]
Setting up the project and testing the maps APIs, contrasting which one to employ and the different functionalities.

**Comment by UO266618** [comment]
> I have introduced the interactive map using the Heremaps API in the application. 
> I added the location of the user in session.

Commit: https://github.com/Arquisoft/radarin_es1a/commit/8aba1ca743894fcffdd35710523142a6de1fd9ec

**Comment by kevin1123699** [comment]
I have introduced pop ups when you click on a marker and satellite view

Commit:
https://github.com/Arquisoft/radarin_es1a/commit/feba968d2286a50752ebfa375ba4f336719deeca
