### ISSUE TITLE
1st Prototype: Login

### ISSUE THREAD

**Issue by UO270176** [Arquisoft/radarin_es1a#31]

**Comment by UO263745** [comment]
We develop a new branch to begin the prototype of the login.

Commit: https://github.com/Arquisoft/radarin_es1a/commit/a3cde9b39b3687a8b11cd06eef765971c68ede7e

**Comment by UO263745** [comment]
We delete the branch that we are developing because problems with the import of library: @inrupt/solid-react-components

**Comment by UO263745** [comment]
The new branch created is: https://github.com/Arquisoft/radarin_es1a/commit/613ced0b67f902eea80412d7a5d5ed04c7300c6e
This was created from the map previews from our teammates.
