### ISSUE TITLE
Map: Marked not displayed

### ISSUE THREAD

**Issue by UO266618** [Arquisoft/radarin_es1a#32]
I have entered an image of a marker for the user's location but entering it in the code does not display correctly on the map. I commented on the code that makes use of the image. At the moment, a default API marker is used.

**Comment by kevin1123699** [comment]
Fixed in commit:
https://github.com/Arquisoft/radarin_es1a/commit/e8d1534c65d3717a1d38e8bb1383a47d42e95102
