### ISSUE TITLE
Solid profiles

### ISSUE THREAD

**Issue by UO266618** [Arquisoft/radarin_es1a#33]
My account: https://victoriaalvarez.solidcommunity.net/profile/card#me

**Comment by UO270176** [comment]
My account: [https://ismaelsolid.solidcommunity.net/profile/card#me](url)

**Comment by uo251434** [comment]
My account: https://tasorodri.solidcommunity.net/profile/card#me

**Comment by albaaparicio12** [comment]
My account: https://albaaparicio.solidcommunity.net/profile/card#me

**Comment by kevin1123699** [comment]
My account: https://kevin1123699.solidcommunity.net/profile/card#me
