### ISSUE TITLE
Mobile application: does not request access to the user's location

### ISSUE THREAD

**Issue by UO266618** [Arquisoft/radarin_es1a#37]
From the computer, the user's location is correctly requested and it is represented on the map but from the mobile browser it does not.

**Comment by UO266618** [comment]
Theory: as the application is deployed locally, http is used and not https. For this reason, the location is not requested on mobiles.

**Comment by kevin1123699** [comment]
It seems that for the location to work in android we strictly need a secure https connection so it seems that it works and we must check it in heroku.

https://stackoverflow.com/a/39122436

**Comment by kevin1123699** [comment]
> It seems that for the location to work in android we strictly need a secure https connection so it seems that it works and we must check it in heroku.
> 
> https://stackoverflow.com/a/39122436

Mobile application does not request access to the user's location in Heroku

Commit:
https://github.com/Arquisoft/radarin_es1a/commit/a55ac12f2f69ac0e9c2595fe991c8a530669d66d
