### ISSUE TITLE
Update the map regularly

### ISSUE THREAD

**Issue by kevin1123699** [Arquisoft/radarin_es1a#41]

**Comment by UO266618** [comment]
Save location every 30 seconds: https://github.com/Arquisoft/radarin_es1a/commit/8dc1c4d40263b69e5cb0752c5510081cc7cc8e97

**Comment by kevin1123699** [comment]
Map markers are read from database
commit: https://github.com/Arquisoft/radarin_es1a/commit/f38292a7b989f3f7c3fb9988bfe2ed660e770260

**Comment by kevin1123699** [comment]
Markers are updated regularly  on the map
commit: https://github.com/Arquisoft/radarin_es1a/commit/f61ff9254f809512fad974566c7b759e0d8bcc1b

**Comment by UO266618** [comment]
The markers show the name of the friends instead of their solidId.

> https://github.com/Arquisoft/radarin_es1a/commit/c5c7445a134410ec218b70d75189bb1e18327aa5
