### ISSUE TITLE
Implement notifications

### ISSUE THREAD

**Issue by albaaparicio12** [Arquisoft/radarin_es1a#51]

**Comment by albaaparicio12** [comment]
Added a dependency and little changes: [dependency](https://github.com/Arquisoft/radarin_es1a/commit/056a55d879c61a7d1efd588afae37e20b4fb1d1f) , [changes](https://github.com/Arquisoft/radarin_es1a/commit/6d53b1673007b62e1baa8df5269080f0c7720f8a)

**Comment by UO247134** [comment]
Herramientas para simular ubicacion y facilitar hacer pruebas de esto:

- Fake GPS Location Spoofer Free [link](https://play.google.com/store/apps/details?id=com.incorporateapps.fakegps.fre)
- Fake GPS [link](https://play.google.com/store/apps/details?id=com.blogspot.newapphorizons.fakegps)
- Simulador GPS [link](https://play.google.com/store/apps/details?id=com.rosteam.gpsemulator)

**Comment by albaaparicio12** [comment]
Tried to implement notifications in the operative system but it didn't work, there was so many bugs and wasn't compatible with iOS users: d280a2a7cfcfbb55978ce1dc3a648b3cf0c7d49d 3399ffbfce74c3679b7bce0ab21dbe1d6d8585fa

So we decided to implement simple notifications inside the application without background execution: fe6235b1e27c16328321308025c339568c70e045

Also added a notification to covid cases: 92d203bfb2e679b679d14bec5c6057d709f8b611
