### ISSUE TITLE
Problem getting solid friends for the map

### ISSUE THREAD

**Issue by UO266618** [Arquisoft/radarin_es1a#61]
When the user's friends are obtained in session, it is done asynchronously and after several executions it is that it manages to obtain the complete friends. I have tried to solve this in the commit: https://github.com/Arquisoft/radarin_es1a/commit/3d2a82387d98e6a80d0031f863b2953d8c73eee0 but then the map does not update them correctly.

**Comment by kevin1123699** [comment]
Problem solved in pair programming with @UO266618
commit:
https://github.com/Arquisoft/radarin_es1a/commit/40646aaf76f5a68a34764ad03979637764d7c94e
