### ISSUE TITLE
By manually entering the login URL, the navigation bar and its options are displayed

### ISSUE THREAD

**Issue by UO266618** [Arquisoft/radarin_es1a#67]

**Comment by UO247134** [comment]
Posible Solution:
Project radarin_es2a solved this issue [](https://github.com/Arquisoft/radarin_es2a)

**Comment by UO247134** [comment]
Solucionado con lo sugerido en:

- [Solucion](https://www.campusvirtual.uniovi.es/mod/forum/discuss.php?d=134462)
