### ISSUE TITLE
Now the friend's list doesn't appear

### ISSUE THREAD

**Issue by UO263745** [Arquisoft/radarin_es1a#70]
Commit when it works: https://github.com/Arquisoft/radarin_es1a/commit/1d8216ed3d26da623ef8e18ecbb96bcae903e877

**Comment by UO266618** [comment]
Fixed with a warning that needs to be resolved.

> https://github.com/Arquisoft/radarin_es1a/commit/f5225687f9866f86927c29d7f6d44aa0c7a132d7
