### ISSUE TITLE
Add Zoom in Friend

### ISSUE THREAD

**Issue by uo251434** [Arquisoft/radarin_es1a#76]
On the Friend list, when you click in a profile, the map will show, zoomed in the user

**Comment by kevin1123699** [comment]
Zoom added
commit:https://github.com/Arquisoft/radarin_es1a/commit/5671bb610b11db0caff9ea49bed2f8ff9dec620b

**Comment by kevin1123699** [comment]
Changes in the funcionality of zoom in friend after fixing the bug #77 
Commit:
https://github.com/Arquisoft/radarin_es1a/commit/83890004197702fea252c4f4a348004912a30cf3
