### ISSUE TITLE
Documentación punto 10

### ISSUE THREAD

**Issue by kevin1123699** [Arquisoft/radarin_es1a#8]

**Comment by kevin1123699** [comment]
Commit:
https://github.com/Arquisoft/radarin_es1a/commit/de5d37e262fad095eb9a6d8df5417bc3420b8f19

**Comment by UO247134** [comment]
1. Change priorities to only medium-high-very high.
2. Reorder table by priorities.
3. Add text clarifying that security and privacy will be prioritized at the cost of efficiency

**Comment by kevin1123699** [comment]
Improve in quality scenarios
commit:https://github.com/Arquisoft/radarin_es1a/commit/9bd646e5c919059ff5c241ba680c584a51815e1c

**Comment by kevin1123699** [comment]
Changes in the Quality Scenarios
commit:https://github.com/Arquisoft/radarin_es1a/commit/475e5a8572e667ef0aaf85da6fd2915a94f842d7
