### ISSUE TITLE
Problems deploying the application on heroku

### ISSUE THREAD

**Issue by UO266618** [Arquisoft/radarin_es1a#86]
The map class and the app class of webapp with the heroku address does not show the friends on the map

**Comment by kevin1123699** [comment]
After looking at the logs it seems that the error is due to not finding a module
![image](https://user-images.githubusercontent.com/59027537/115997790-b7389f80-a5e4-11eb-8d75-a433d646de2f.png)

**Comment by kevin1123699** [comment]
after commenting on the module, I managed to upload to heroku
commit:https://github.com/Arquisoft/radarin_es1a/commit/1eb1fe190afd950dbf5ee0c21dab2313e78e55d6
